#ifndef _DEFINES_H
#define _DEFINES_H

#define true 1
#define false 0

//COLORS
#define RENDER_COLOR_RED 0xFF, 0x00, 0x00, 0x00
#define RENDER_COLOR_GREEN 0xAD, 0xFF, 0xAD, 0x00
#define RENDER_COLOR_BLACK 0x00, 0x00, 0x00, 0x00
#define RENDER_COLOR_ORANGE 0xFF, 0xA7, 0x00, 0x00

#define RENDER_COLOR_INFECTED RENDER_COLOR_ORANGE
#define RENDER_COLOR_IMMUNE RENDER_COLOR_GREEN
#define RENDER_COLOR_DEAD RENDER_COLOR_RED


#endif //_DEFINES_H
